/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-04-08 04:13:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Bootstrap Login &amp; Register Templates</title>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://fonts.googleapis.com/css?family=Roboto:400,100,300,500\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/form-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style-register.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Top content -->\r\n");
      out.write("\t<div class=\"top-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"inner-bg\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-8 col-sm-offset-2 text\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Website name</h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>Some Description</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-top-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Already registered? Login here</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Enter username and password to login</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-top-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-key\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form role=\"form\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taction=\"http://localhost:8181/Ecommerce/rest/loginService\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmethod=\"POST\" class=\"login-form\" id=\"form-login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"color: #FF0000;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"sr-only\" for=\"form-username\">Username</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"form-username\" placeholder=\"Username...\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-username form-control\" id=\"form-username\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"sr-only\" for=\"form-password\">Password</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"form-password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Password...\" class=\"form-password form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"form-password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\">Login</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-1 middle-border\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-1\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-top-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>New User? Register here</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Fill in the form below to start shopping</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-top-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-pencil\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form role=\"form\" action=\"\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"registration-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"sr-only\" for=\"form-first-name\">First\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname</label> <input type=\"text\" name=\"form-first-name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"First name...\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-first-name form-control\" id=\"form-first-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"sr-only\" for=\"form-last-name\">Last name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"form-last-name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Last name...\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-last-name form-control\" id=\"form-last-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"sr-only\" for=\"form-email\">Email</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"form-email\" placeholder=\"Email...\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-email form-control\" id=\"form-email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"sr-only\" for=\"form-about-yourself\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"form-password\" placeholder=\"Password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-password form-control\" id=\"form-password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\">Register</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-8 col-sm-offset-2\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-border\"></div>\r\n");
      out.write("\t\t\t\t<p>Copyright &copy; Website name 2016</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Javascript -->\r\n");
      out.write("\t<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction validate() {\r\n");
      out.write("\t\t\tvar username = document.getElementById(\"form-username\");\r\n");
      out.write("\t\t\tvar password = document.getElementById(\"form-password\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.post(\"http://localhost:8181/Ecommerce/rest/loginService\",\r\n");
      out.write("\t\t\t\t\t$(\"#form-login\").serialize()).done(function(data) {\r\n");
      out.write("\t\t\t\talert(data + \"---asdsadas\");\r\n");
      out.write("\t\t\t\t//             if( data === username ) {\r\n");
      out.write("\t\t\t\t//                 alert( \"Success\" );\r\n");
      out.write("\t\t\t\t//             }\r\n");
      out.write("\t\t\t\t//             else {\r\n");
      out.write("\t\t\t\t//                 alert( \"Wrong username or password\" );\r\n");
      out.write("\t\t\t\t//             }\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--[if lt IE 10]>\r\n");
      out.write("            <script src=\"assets/js/placeholder.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
